[shell]
program = "/usr/bin/fish"
# start fish as a login shell
args = ["-l"]




[font]
size = 12.0

[font.normal]
family = "SauceCodePro Nerd Font Mono"
style = "Regular"

[font.bold]
family = "SauceCodePro Nerd Font Mono"
style = "Bold"

[font.italic]
family = "SauceCodePro Nerd Font Mono"
style = "Italic"




[cursor]
style = { shape = "Block", blinking = "On" }
unfocused_hollow = true


[window]
opacity = 1.0
padding = { x = 5, y = 5 }
dynamic_title = true

[window.dimensions]
columns = 120
lines = 35

[scrolling]
history = 10000
multiplier = 3


# Theme: Tokyo Night Storm
[colors.primary]
background = '#1a1b26'
foreground = '#c0caf5'

[colors.normal]
black   = '#32344a'
red     = '#ff718a'
green   = '#b0ef8a'
yellow  = '#ffc777'
blue    = '#7aa2f7'
magenta = '#d399ff'
cyan    = '#83eaff'
white   = '#878ca8'

[colors.bright]
black   = '#50567c'
red     = '#ff7a93'
green   = '#c8ff99'
yellow  = '#ffb675'
blue    = '#83b2ff'
magenta = '#d39fff'
cyan    = '#9af0ff'
white   = '#c8cde7'
